name = "uintdev-main"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-06-04"

routes = [
    { pattern = "uint.dev", custom_domain = true },
    { pattern = "www.uint.dev/*", custom_domain = false }
]

workers_dev = false
preview_urls = false

[assets]
directory = "./dist/"
not_found_handling = "404-page"
